@ECHO OFF

REM init env locally

CD %~dp0
SET WORK=%CD%
ECHO WORK=%WORK%

SET DEBUG_WIN=1

SET PYTHONPATH=%WORK%\mindformers
SET PYTHONPATH=%WORK%\llm-serving;%PYTHONPATH%
SET PYTHONPATH=%WORK%\llm-serving\mindspore_serving;%PYTHONPATH%
SET GRAPH_OP_RUN=1
SET MS_ENABLE_INTERNAL_KERNELS=on

ECHO PYTHONPATH=%PYTHONPATH%

CMD /K conda activate llm && ECHO %PYTHONPATH%
