run_mode: 'predict'
seed: 0

# mindspore context init config
context:
  mode: 0               # 0--Graph Mode; 1--Pynative Mode
  device_target: "CPU"
  max_call_depth: 10000
  max_device_memory: "28GB"
  save_graphs: True
  save_graphs_path: "./graph/llama2"
  device_id: 0

# model config
model:
  model_config:
    type: LlamaConfig
    batch_size: 1       # add for increase predict
    seq_length: 32
    hidden_size: 4096
    num_layers: 32
    num_heads: 32
    vocab_size: 32000
    multiple_of: 256
    rms_norm_eps: 1.0e-5
    bos_token_id: 1
    eos_token_id: 2
    pad_token_id: 0
    ignore_token_id: -100
    compute_dtype: "float16"
    layernorm_compute_type: "float16"   # float32
    softmax_compute_type: "float16"     # float32
    rotary_dtype: "float16"
    param_init_type: "float16"
    use_past: False              # support from mindspore==2.3, FA is not available on CPU
    use_flash_attention: False   # FA is not available on CPU
    scaling_factor: 1.0          # The scale factor of seq length
    extend_method: "None"        # support "None", "PI", "NTK"
    block_size: 16
    num_blocks: 1024
    is_dynamic: False
    offset: 0
    checkpoint_name_or_path: "checkpoint_download/llama2/llama2_7b.ckpt"
    repetition_penalty: 1
    max_decode_length: 32
    top_k: 3
    top_p: 1
    do_sample: False
  arch:
    type: LlamaForCausalLM

processor:
  return_tensors: ms
  tokenizer:
    unk_token: '<unk>'
    bos_token: '<s>'
    eos_token: '</s>'
    pad_token: '<unk>'
    type: LlamaTokenizer
  type: LlamaProcessor

profile: False
profile_start_step: 1
profile_stop_step: 10
init_start_profile: False
profile_communication: False
profile_memory: True
layer_scale: False
layer_decay: 0.65
lr_scale_factor: 256
